### ISSUE TITLE
Missing '/vendor/autoload.php'

### ISSUE THREAD

**Issue by kosvrouvas** [panvagenas/skroutz-xml-feed#7]
Warning: require_once(/var/www/xxxxxxxxx.gr/wp-content/plugins/skroutz-xml-feed-master/vendor/autoload.php): failed to open stream: No such file or directory in /var/www/xxxxxxxxx.gr/wp-content/plugins/skroutz-xml-feed-master/plugin.php on line 55 Fatal error: require_once(): Failed opening required '/var/www/xxxxxxxxx.gr/wp-content/plugins/skroutz-xml-feed-master/vendor/autoload.php' (include_path='.:/usr/share/php5:/usr/share/php') in /var/www/xxxxxxxxxx.gr/wp-content/plugins/skroutz-xml-feed-master/plugin.php on line 55

**Comment by panvagenas** [comment]
Have you tried to run `composer install`? 
This error usually occurs when dependencies are not installed.

**Comment by kosvrouvas** [comment]
hm, my bad.

**Comment by babismysta** [comment]
Hi, I have the same issue. Cant activate the plugin. What is a composer install? how can i do this? i am new to this sorry for the rookie questions.

**Comment by babismysta** [comment]
I cant do this man i have not the permission to the server i just wanted this plugin why cant you just make it like every one other plugin install activate done. Can you explain?

**Comment by panvagenas** [comment]
Sorry mate for having this plugin the way I want and not the way you want. Nothing I can do about it. Cheers!

**Comment by babismysta** [comment]
Whats the point to have a plugin no one can run? What can i do now? I cant access the server its a shared simple hosting my webiste
