### ISSUE TITLE
Product Size & Color

### ISSUE THREAD

**Issue by peramosmegara** [panvagenas/skroutz-xml-feed#8]
The plugin works fine, but we have not been able to get the size (νούμερο) and color (χρώμα) to export to the xml document. It is a sports shop. The attributes are left plank. If we tick 'use size/color variations' it leaves them blank like so:
size
color
How can we export the attributes of the variable woocommerce products?
Thank you,

**Comment by panvagenas** [comment]
You'll have to select the appropriate options just under the checkbox, but in order for this to work color's and/or size's must be defined as product attributes.
